### ISSUE TITLE
Possible missing dependency

### ISSUE THREAD

**Issue by kfjustis** [JadedTuna/chip8#1]
I tried to compile the code when I ran into an "undefined reference to _boxRGBA()_" error. After some searching, it appears that _boxRGBA()_ is from another library, _SDL_gfx_, which I found [here](http://www.ferzkopp.net/wordpress/2016/01/02/sdl_gfx-sdl2_gfx/).

If there's still interest, it would be useful to add something to the README about it. Also, if this doesn't seem right, please let me know!

Note: I compiled using a MinGW environment on Windows 10 with the following command: 
`$ gcc chip8.c -o chip8 -lmingw32 -lSDLmain -lSDL`

**Comment by JadedTuna** [comment]
@kfjustis sorry for the very late reply. `boxRGBA()` was something I used before I switched to `SDL_FillRect()`, apparently that was one place I forgot to change it. I fixed that now, along some other stuff, so the emulator should fine work now.
